version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run dev
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/codelumus?schema=public
      - NODE_ENV=development
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - GITHUB_ID=
      - GITHUB_SECRET=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - STRIPE_API_KEY=
      - STRIPE_WEBHOOK_SECRET=
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
      - RESEND_API_KEY=
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=codelumus
    ports:
      - 5432:5432
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d codelumus"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge 